# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'easy_editor_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.papka = QtWidgets.QPushButton(self.centralwidget)
        self.papka.setGeometry(QtCore.QRect(10, 10, 191, 23))
        self.papka.setObjectName("papka")
        self.files = QtWidgets.QListWidget(self.centralwidget)
        self.files.setGeometry(QtCore.QRect(10, 50, 191, 541))
        self.files.setObjectName("files")
        self.black_white = QtWidgets.QPushButton(self.centralwidget)
        self.black_white.setGeometry(QtCore.QRect(640, 570, 75, 23))
        self.black_white.setObjectName("black_white")
        self.rizkist = QtWidgets.QPushButton(self.centralwidget)
        self.rizkist.setGeometry(QtCore.QRect(540, 570, 75, 23))
        self.rizkist.setObjectName("rizkist")
        self.left = QtWidgets.QPushButton(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(240, 570, 75, 23))
        self.left.setObjectName("left")
        self.mirror = QtWidgets.QPushButton(self.centralwidget)
        self.mirror.setGeometry(QtCore.QRect(440, 570, 75, 23))
        self.mirror.setObjectName("mirror")
        self.right = QtWidgets.QPushButton(self.centralwidget)
        self.right.setGeometry(QtCore.QRect(340, 570, 75, 23))
        self.right.setObjectName("right")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 10, 561, 541))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.papka.setText(_translate("MainWindow", "Папка"))
        self.black_white.setText(_translate("MainWindow", "Ч/Б"))
        self.rizkist.setText(_translate("MainWindow", "Різкість"))
        self.left.setText(_translate("MainWindow", "Вліво"))
        self.mirror.setText(_translate("MainWindow", "Дзеркало"))
        self.right.setText(_translate("MainWindow", "вправо"))
        self.label.setText(_translate("MainWindow", "Картинка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
