# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\py_projects\Logika_projects\easy_editor\easy_editor_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 750, 601))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.main_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.files_layout = QtWidgets.QVBoxLayout()
        self.files_layout.setObjectName("files_layout")
        self.papka = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.papka.setObjectName("papka")
        self.files_layout.addWidget(self.papka)
        self.files = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.files.setObjectName("files")
        self.files_layout.addWidget(self.files)
        self.main_layout.addLayout(self.files_layout)
        self.image_layout = QtWidgets.QVBoxLayout()
        self.image_layout.setObjectName("image_layout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.image_layout.addWidget(self.label)
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        self.right = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.right.setObjectName("right")
        self.buttons_layout.addWidget(self.right)
        self.left = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.left.setObjectName("left")
        self.buttons_layout.addWidget(self.left)
        self.blur = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.blur.setObjectName("blur")
        self.buttons_layout.addWidget(self.blur)
        self.mirror = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.mirror.setObjectName("mirror")
        self.buttons_layout.addWidget(self.mirror)
        self.rizkist = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.rizkist.setObjectName("rizkist")
        self.buttons_layout.addWidget(self.rizkist)
        self.black_white = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.black_white.setObjectName("black_white")
        self.buttons_layout.addWidget(self.black_white)
        self.image_layout.addLayout(self.buttons_layout)
        self.main_layout.addLayout(self.image_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.papka.setText(_translate("MainWindow", "Папка"))
        self.label.setText(_translate("MainWindow", "Картинка"))
        self.right.setText(_translate("MainWindow", "вправо"))
        self.left.setText(_translate("MainWindow", "Вліво"))
        self.blur.setText(_translate("MainWindow", "Розмити"))
        self.mirror.setText(_translate("MainWindow", "Дзеркало"))
        self.rizkist.setText(_translate("MainWindow", "Різкість"))
        self.black_white.setText(_translate("MainWindow", "Ч/Б"))
